# Generated by Django 5.2.7 on 2025-10-28 19:17

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userservice',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
