# Generated by Django 5.2.7 on 2025-11-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_delete_mailingattempt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userservice",
            options={
                "permissions": [
                    ("view_service_users", "Просмотр списка пользователей"),
                    ("block_users", "Блокировка пользователей"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
