# Generated by Django 5.2.7 on 2025-11-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mailingattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="is_success",
            field=models.BooleanField(default=False, verbose_name="Успешно"),
        ),
    ]
