# Generated by Django 5.2.7 on 2025-11-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_mailingattempt_owner_message_owner_recipient_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailingattempt",
            name="owner",
        ),
    ]
