# Generated by Django 5.2.7 on 2025-11-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_remove_mailingattempt_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="recipient",
            name="owner",
        ),
    ]
