# Generated by Django 5.2.7 on 2025-11-26 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_remove_message_owner_remove_recipient_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("view_all_clients_and_mailings", "Просмотр всех клиентов и рассылок"),
                    ("view_user_list", "Просмотр списка пользователей сервиса"),
                    ("block_users", "Блокировка пользователей сервиса"),
                    ("disable_mailings", "Отключение рассылок"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("view_all_clients_and_mailings", "Просмотр всех клиентов и рассылок"),
                    ("view_user_list", "Просмотр списка пользователей сервиса"),
                    ("block_users", "Блокировка пользователей сервиса"),
                    ("disable_mailings", "Отключение рассылок"),
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [
                    ("view_all_clients_and_mailings", "Просмотр всех клиентов и рассылок"),
                    ("view_user_list", "Просмотр списка пользователей сервиса"),
                    ("block_users", "Блокировка пользователей сервиса"),
                    ("disable_mailings", "Отключение рассылок"),
                ],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="recipient",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
