# Generated by Django 5.2.7 on 2025-11-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_alter_mailing_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("view_all_mailings", "Просмотр всех рассылок"),
                    ("disable_mailings", "Отключение рассылок"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("view_all_messages", "Просмотр всех сообщений")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [("view_all_recipients", "Просмотр всех клиентов")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
